# Generated by Django 2.2.1 on 2019-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190526_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
