# Generated by Django 2.2.1 on 2019-05-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190526_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('interest_rate', models.FloatField(max_length=3)),
            ],
            options={
                'db_table': 'Loan',
            },
        ),
        migrations.CreateModel(
            name='Monthly_payment',
            fields=[
                ('monthly_payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('monthly_payment', models.FloatField(max_length=10)),
                ('expiration_payment', models.FloatField(max_length=10)),
            ],
            options={
                'db_table': 'Monthly_payment',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Property',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=10)),
                ('date_granted', models.DateField()),
                ('date_repaid', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Customer')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Loan')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.CreateModel(
            name='Monthly_payment_record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_this', models.DateField()),
                ('date_last', models.DateField()),
                ('is_month_paid', models.BooleanField()),
            ],
            options={
                'db_table': 'Monthly_payment_record',
                'unique_together': {('record_id', 'date_this')},
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Monthly_payment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='property_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property'),
        ),
    ]
