# Generated by Django 2.2.1 on 2019-05-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190527_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='property_type_id',
            field=models.ForeignKey(default='property_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property'),
        ),
    ]
