# Generated by Django 2.2.1 on 2019-05-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190527_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='amount',
        ),
    ]
