# Generated by Django 2.2.1 on 2019-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_remove_record_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=(0, 0), max_digits=10),
            preserve_default=False,
        ),
    ]
