# Generated by Django 2.2.1 on 2019-05-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_record_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='amount',
        ),
    ]
