# Generated by Django 2.2.1 on 2019-05-30 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20190527_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'db_table': 'City',
                'ordering': ['city_id'],
            },
        ),
        migrations.CreateModel(
            name='Property_title',
            fields=[
                ('property_title_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Назва власності',
                'verbose_name_plural': 'Назви власностей',
                'db_table': 'Property_title',
                'ordering': ['property_title_id'],
            },
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('property_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Тип власності',
                'verbose_name_plural': 'Типи власностей',
                'db_table': 'Property_type',
                'ordering': ['property_type_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id'], 'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['loan_id'], 'verbose_name': 'Кредит', 'verbose_name_plural': 'Кредити'},
        ),
        migrations.AlterModelOptions(
            name='monthly_payment',
            options={'ordering': ['monthly_payment_id'], 'verbose_name': 'Місячна сплата', 'verbose_name_plural': 'Місячні сплати'},
        ),
        migrations.AlterModelOptions(
            name='monthly_payment_record',
            options={'verbose_name': 'Облік місячних сплат', 'verbose_name_plural': 'Облік місячних сплат'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['person_id'], 'verbose_name': 'Представник', 'verbose_name_plural': 'Представники'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['property_id'], 'verbose_name': 'Власність', 'verbose_name_plural': 'Власності'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['record_id'], 'verbose_name': 'Облік кредитів', 'verbose_name_plural': 'Облік кредитів'},
        ),
        migrations.RenameField(
            model_name='monthly_payment_record',
            old_name='date_last',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type_id',
            new_name='property_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='edrpou',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthly_payment_record',
            name='record',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='landing.Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='assessed_value',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='month_paid',
            field=models.DecimalField(blank=True, decimal_places=8, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property', to_field='property_type_id'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Monthly_payment'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property_type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_repaid',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthly_payment_record',
            unique_together={('record', 'date')},
        ),
        migrations.CreateModel(
            name='Property_address',
            fields=[
                ('property_address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.City')),
            ],
            options={
                'verbose_name': 'Адреса власності',
                'verbose_name_plural': 'Адреси власностей',
                'db_table': 'Property_address',
                'ordering': ['property_address_id'],
            },
        ),
        migrations.RemoveField(
            model_name='monthly_payment_record',
            name='date_this',
        ),
        migrations.RemoveField(
            model_name='monthly_payment_record',
            name='is_month_paid',
        ),
        migrations.RemoveField(
            model_name='monthly_payment_record',
            name='record_id',
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property_address'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_title',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property_title'),
            preserve_default=False,
        ),
    ]
