# Generated by Django 2.0.7 on 2019-05-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20190530_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Property'),
        ),
    ]
