# Generated by Django 2.0.7 on 2019-05-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20190530_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='amount_remaining',
            field=models.FloatField(),
        ),
    ]
